# Generated by Django 2.2.3 on 2019-07-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='youwork',
            field=models.CharField(choices=[('new', '신규'), ('work', '출근'), ('notwork', '결근')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
