# Generated by Django 2.2.3 on 2019-07-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halfapp', '0002_account_youwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='youwork',
        ),
    ]
