# Generated by Django 2.2.3 on 2019-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halfapp', '0005_workrecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecode',
            name='name',
        ),
    ]
