# Generated by Django 2.2.3 on 2019-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfapp', '0006_remove_workrecode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecode',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
